export const ADD_SHOP_BEGIN = 'ADD_SHOP_BEGIN';
export const ADD_SHOP_SUCCESS = 'ADD_SHOP_SUCCESS';
export const ADD_SHOP_FAIL = 'ADD_SHOP_FAIL';
export const ADD_SHOP_FINALLY = 'ADD_SHOP_FINALLY';

export const DELETE_SHOP_BEGIN = 'DELETE_SHOP_BEGIN';
export const DELETE_SHOP_SUCCESS = 'DELETE_SHOP_SUCCESS';
export const DELETE_SHOP_FAIL = 'DELETE_SHOP_FAIL';
export const DELETE_SHOP_FINALLY = 'DELETE_SHOP_FINALLY';

export const UPDATE_SHOP_BEGIN = 'UPDATE_SHOP_BEGIN';
export const UPDATE_SHOP_SUCCESS = 'UPDATE_SHOP_SUCCESS';
export const UPDATE_SHOP_FAIL = 'UPDATE_SHOP_FAIL';
export const UPDATE_SHOP_FINALLY = 'UPDATE_SHOP_FINALLY';

export const SEARCH_SHOP_BEGIN = 'SEARCH_SHOP_BEGIN';
export const SEARCH_SHOP_SUCCESS = 'SEARCH_SHOP_SUCCESS';
export const SEARCH_SHOP_FAIL = 'SEARCH_SHOP_FAIL';
export const SEARCH_SHOP_FINALLY = 'SEARCH_SHOP_FINALLY';

export const CHANGE_SHOP_BEGIN = 'CHANGE_SHOP_BEGIN';
export const CHANGE_SHOP_SUCCESS = 'CHANGE_SHOP_SUCCESS';
export const CHANGE_SHOP_FAIL = 'CHANGE_SHOP_FAIL';
export const CHANGE_SHOP_FINALLY = 'CHANGE_SHOP_FINALLY';

